stages:
  stage_1:
    cmd: python stage_01.py
    deps: 
      - stage_01.py
    outs:
      - artifacts.txt

  stage_2:
    cmd: python stage_02.py
    deps:
      - artifacts.txt
      - stage_02.py

  stage_3:
    cmd: python stage_03.py
    deps:
      - artifacts.txt
      - stage_03.py